version: '3.7'
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.16.0
    ulimits:
      memlock:
        soft: -1
        hard: -1
    environment:
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - discovery.type=single-node
    ports: 
      - 9200:9200
      - 9300:9300

  logstach:
    image: docker.elastic.co/logstash/logstash:7.16.0
  
  kibana:
    image: docker.elastic.co/kibana/kibana:7.16.0
    ports:
      - 5601:5601
