version: "3.7"

services:
  nginx-server:
    image: nginx:alpine
    container_name: webserver
    restart: always
    tty: true
    ports:
      - "80:80"
      - "443:443"
    networks:
      - web-network

  ubuntu-server:
    image: ubuntu:alpine
    container_name: log-generator
    restart: always
    tty: true
    ports:
      - "151:151"
    networks:
      - web-network